apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: project-a-backend
  namespace: project-a
  labels:
    app: project-a-backend
spec:
  replicas: 2
  revisionHistoryLimit: 3

  selector:
    matchLabels:
      app: project-a-backend

  template:
    metadata:
      labels:
        app: project-a-backend
    spec:
      containers:
        - name: backend
          image: cowmin/project-a-backend:0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

  strategy:
    canary:
      stableService: project-a-backend
      canaryService: project-a-backend-canary
      steps:
        - setWeight: 20
        - pause: { duration: 30s }
        - setWeight: 50
        - pause: { duration: 30s }
        - setWeight: 100