apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-a-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/somminn/project-a-gitops.git
    targetRevision: main
    path: app/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: project-a
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
